apiVersion: v1
kind: Service
metadata:
  name: ms-service
  labels:
    app: ms-service
spec:
  type: NodePort
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
  selector:
    app: ms-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-service
  template:
    metadata:
      labels:
        app: ms-service
    spec:
      containers:
        - name: ms-service
          image: ms-service
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "500m"
             memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
          ports:
            - containerPort: 80
            - containerPort: 443
